# These are supported funding model platforms

github: [richierockskool]

buy_me_a_coffee: Buy Me a Coffee richierockskool
thanks_dev: # Replace with a single thanks.dev username
custom: [https://link.clover.com/urlshortener/3WBgr7]
